[project]
name = "code-edditor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.9.1",
    "pywinpty>=2.0.15",
]
